### PR TITLE
Update packaging to build with libdaos.so.1

### PR DESCRIPTION
**Pull request by kccain**
PR-repos: daos@PR-3935:15
PR-repos: mpich@PR-44

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

### CODE REVIEW

**Review by brianjmurrell — COMMENTED** [review]
Does hdf5 actually link with/use libdaos.so directly?  I can't see any evidence that it does:

```
$ rpm -qRp ~/Downloads/hdf5-mpich-1.12.0-6.gfa40c6c59a.el7.x86_64.rpm  | grep daos
```

If it does not, then a rebuild of this is not necessary and you can remove the `hdf5@PR-18` from your other PRs including daos-stack/daos#3935.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
Going to -1 until the need for this rebuild is determined, as I don't think it's actually needed.

**Comment by kccain** [comment]
Isn't a rebuild of hdf5 needed because of it's dependency on mpich? @mjean308 is that right?

**Comment by mjean308** [comment]
I believe it was the update of hdf5-vol (which does depend on daos )  that caused hdf5 rpm to have to be updated.    You are using a later version of hdf5 vol and that required a later version of hdf5

**Comment by brianjmurrell** [comment]
> Isn't a rebuild of hdf5 needed because of it's dependency on mpich?

Only if the ABI of mpich changed, which I don't think it has, correct?

**Comment by brianjmurrell** [comment]
> I believe it was the update of hdf5-vol (which does depend on daos ) that caused hdf5 rpm to have to be updated.

It's not obvious why that would be necessary.

> You are using a later version of hdf5 vol and that required a later version of hdf5

But that is independent of this PR and this PR does not change the version of anything.

**Comment by kccain** [comment]
This PR is not needed, closing.

**Pull request closed without merging**
