### PR TITLE
DAOS-5407 build: Add enable-map-api to configure

### PR DESCRIPTION
**Pull request by mjean308**
Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Review by mchaarawi — APPROVED** [review]

**Review by phender — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Are you confident that this will not break hdf5 testing on current master?  I'll land if you are.  Or you can run a `PR-repos:` test if you want to be sure.

Ideally the test stage of this PR would do that `PR-repos:` test for you, but it's just not gotten the resources to write that test yet, unfortunately.

**Comment by mjean308** [comment]
I have run manually, but I will create a daos PR to run just the HDF5 test

**Comment by mjean308** [comment]
Submitted PR-3229 to test this update:

PR-repos: hdf5@PR-12
Test-tag-hw-small: hdf5
Skip-checkpatch: true
Skip-run_test: true
Skip-func-test: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

**Comment by mjean308** [comment]
PR-3229 has passed the hdf5 test with the rpms from this PR.

**Pull request merged**
